Repository Interacao-Humano-Computador/2021.2-Prefeitura-Verdelandia, pull requests merged in 2022-02, with the labels that each got.

#2 Adiciona o documento de metodologia à documentação
  docs/documentos/Metodologia.md
  mkdocs.yml
Labels: documentation

#15 Correções - Ajusta a navbar
  mkdocs.yml
Labels: feedback, fix

#16 Introdução criada para o cronograma
  docs/documentos/Cronograma.md
Labels: documentation, feedback

#17 #9: Fixed the problems after the feedback
  docs/documentos/Ferramentas.md
Labels: feedback, fix

#20 Doc/personas
  docs/assets/antipersonaCapone.png
  docs/assets/personaCamila.png
  docs/assets/personaLara.png
  docs/assets/personaLuis.png
  docs/documentos/Personas.md
  docs/documentos/SiteEscolhido.md
  mkdocs.yml
Labels: documentation

#25 Docs/perfil usuario
  README.md
  docs/assets/questionario/q1.png
  docs/assets/questionario/q2.png
  docs/assets/questionario/q3.png
  docs/assets/questionario/q4.png
  docs/assets/questionario/q5.png
  docs/assets/questionario/q6.png
  docs/assets/questionario/q7.png
  docs/assets/questionario/q8.png
  docs/documentos/Apresentacao_PC1.md
  docs/documentos/Cronograma.md
  docs/documentos/Ferramentas.md
  docs/documentos/Metodologia.md
  docs/documentos/PerfilUsuario.md
  docs/documentos/Processos.md
  docs/documentos/SiteEscolhido.md
  docs/documentos/SitesAvaliados.md
  docs/index.md
  mkdocs.yml
Labels: documentation
